name: preview

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - ".github/workflows/check.yml"
      - ".github/workflows/test.yml"
      - ".gitignore"
      - "LICENSE"
      - "tests/**"
      - "tsconfig.json"
      - "tsup.*"
      - "vitest.*"
      - "*.jsonc"
      - "*.md"
      - "*.yml"

jobs:
  release:
    name: Release preview build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Release preview version
        run: pnpm release:preview
