name: tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run-node-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 23.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docker compose
        run: docker compose up -d

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
